import React from "react";
import { useState } from "react";
import Head from "next/head";
import { Link, animateScroll as scroll } from "react-scroll";
import { AiFillGithub, AiFillLinkedin, AiFillHtml5 } from "react-icons/ai";
import { DiCss3, DiReact } from "react-icons/di";
import { SiTailwindcss, SiSass, SiJavascript, SiRedux } from "react-icons/si";
import { BsBoxArrowUpRight, BsFillTelephoneFill } from "react-icons/bs";
import { BiMailSend } from "react-icons/bi";
import Image from "next/image";

export default function Home() {
  const [isNavOpen, setIsNavOpen] = useState(false);

  return (
    <>
      <Head>
        <title>Christian Lau Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header className="sticky top-0 z-30 w-full bg-white shadow-xl">
        <nav className="p-8 flex justify-between items-center">
          <Link
            activeClass="active"
            to="home"
            spy={true}
            smooth={true}
            offset={-70}
            duration={500}
          >
            <h1 className="text-xl font-semibold cursor-default">
              christian.dev
            </h1>
          </Link>
          <div
            className="HAMBURGER-ICON space-y-2 lg:hidden block"
            onClick={() => setIsNavOpen((prev) => !prev)} // toggle isNavOpen state on click
          >
            <span className="block h-0.5 w-8  bg-gray-600"></span>
            <span className="block h-0.5 w-8  bg-gray-600"></span>
            <span className="block h-0.5 w-8  bg-gray-600"></span>
          </div>
          <div className={isNavOpen ? "showMenuNav" : "hideMenuNav"}>
            {" "}
            <div
              className="CROSS-ICON absolute flex flex-col justify-center w-full top-0 right-0 px-8 py-8"
              onClick={() => setIsNavOpen(false)} // change isNavOpen state to false to close the menu
            >
              <div className="flex justify-end">
                <svg
                  className="h-8 w-8 text-gray-600"
                  viewBox="0 0 24 24"
                  fill="none"
                  stroke="currentColor"
                  strokeWidth="2"
                  strokeLinecap="round"
                  strokeLinejoin="round"
                >
                  <line x1="18" y1="6" x2="6" y2="18" />
                  <line x1="6" y1="6" x2="18" y2="18" />
                </svg>
              </div>
              <ul className="flex flex-col gap-6 mt-20 items-center text-xl">
                <li>
                  <Link
                    className="text-neutral-900 font-semibold px-4 py-2 cursor-default"
                    activeClass="active"
                    to="home"
                    spy={true}
                    smooth={true}
                    offset={-70}
                    duration={500}
                    onClick={() => setIsNavOpen(false)}
                  >
                    Home
                  </Link>
                </li>
                <li>
                  <Link
                    className="text-neutral-900 font-semibold px-4 py-2 cursor-default"
                    activeClass="active"
                    to="about"
                    spy={true}
                    smooth={true}
                    offset={-70}
                    duration={500}
                    onClick={() => setIsNavOpen(false)}
                  >
                    About
                  </Link>
                </li>
                <li>
                  <Link
                    className="text-neutral-900 font-semibold px-4 py-2 cursor-default"
                    activeClass="active"
                    to="projects"
                    spy={true}
                    smooth={true}
                    offset={-70}
                    duration={500}
                    onClick={() => setIsNavOpen(false)}
                  >
                    Projects
                  </Link>
                </li>
                <li>
                  <Link
                    className="text-neutral-900 font-semibold px-4 py-2 cursor-default"
                    activeClass="active"
                    to="contact"
                    spy={true}
                    smooth={true}
                    offset={-70}
                    duration={500}
                    onClick={() => setIsNavOpen(false)}
                  >
                    Contact
                  </Link>
                </li>
              </ul>
            </div>
          </div>
          <ul className="lg:flex hidden items-center text-xl">
            <li>
              <Link
                className="text-neutral-900 font-semibold px-4 py-2 cursor-default"
                activeClass="active"
                to="home"
                spy={true}
                smooth={true}
                offset={-70}
                duration={500}
              >
                Home
              </Link>
            </li>
            <li>
              <Link
                className="text-neutral-900 font-semibold px-4 py-2 cursor-default"
                activeClass="active"
                to="about"
                spy={true}
                smooth={true}
                offset={-70}
                duration={500}
              >
                About
              </Link>
            </li>
            <li>
              <Link
                className="text-neutral-900 font-semibold px-4 py-2 cursor-default"
                activeClass="active"
                to="projects"
                spy={true}
                smooth={true}
                offset={-70}
                duration={500}
              >
                Projects
              </Link>
            </li>
            <li>
              <Link
                className="text-neutral-900 font-semibold px-4 py-2 cursor-default"
                activeClass="active"
                to="contact"
                spy={true}
                smooth={true}
                offset={-70}
                duration={500}
              >
                Contact
              </Link>
            </li>
          </ul>
        </nav>
      </header>
      <main className="bg-slate-50">
        <section title="home" id="home" className="min-h-screen px-10">
          <div className="lg:max-w-5xl lg:m-auto lg:pt-28">
            <div className="lg:flex lg:justify-center">
              <div className="lg:flex lg:flex-row-reverse lg:items-center lg:gap-28 text-center pt-10 text-neutral-700">
                <div className="flex justify-center mx-auto rounded-full overflow-hidden min-w-fit">
                  <img
                    className="lg:max-w-lg h-72 lg:min-w-full lg:h-80"
                    src="/profile-good.png"
                    alt="profile-picture"
                  />
                </div>
                <div className="lg:max-w-xl lg:text-left pt-10">
                  <h2 className="lg:text-6xl text-4xl font-bold">
                    Front-End React Developer
                  </h2>
                  <p className="text-lg py-5 leading-8 font-normal text-neutral-500">
                    Hi, I&apos;m Christian Lau. A passionate Front-end React
                    Developer based in Salt Lake City, Utah. 📍
                  </p>
                  <div className="lg:justify-start text-4xl flex justify-center gap-2 py-3">
                    <a
                      href="https://www.linkedin.com/in/christian-lau-436431260/"
                      target="_blank"
                    >
                      <AiFillLinkedin />
                    </a>
                    <a href="https://github.com/cc-lau" target="_blank">
                      <AiFillGithub />
                    </a>
                  </div>
                </div>
              </div>
            </div>
          </div>
          <div className="flex text-neutral-800 justify-center items-center flex-col p-10 lg:p-0 lg:pt-16">
            <h4 className="text-2xl font-semibold text-center py-2 border-b-2 w-fit">
              Tech Stack
            </h4>
            <div className="text-4xl flex flex-wrap justify-center gap-5 py-10">
              <div className=" bg-white rounded-full w-fit p-3 shadow-md">
                <AiFillHtml5 />
              </div>
              <div className=" bg-white rounded-full w-fit p-3 shadow-md">
                {" "}
                <DiCss3 />
              </div>

              <div className=" bg-white rounded-full w-fit p-3 shadow-md">
                {" "}
                <SiJavascript />
              </div>

              <div className=" bg-white rounded-full w-fit p-3 shadow-md">
                {" "}
                <SiRedux />
              </div>

              <div className=" bg-white rounded-full w-fit p-3 shadow-md">
                {" "}
                <DiReact />
              </div>

              <div className=" bg-white rounded-full w-fit p-3 shadow-md">
                <SiTailwindcss />
              </div>

              <div className=" bg-white rounded-full w-fit p-3 shadow-md">
                {" "}
                <SiSass />
              </div>
            </div>
          </div>
        </section>

        {/* ABOUT ME SECTION */}
        <section title="about" id="about" className="bg-white px-10">
          <div className="lg:flex lg:justify-center">
            <div className="lg:max-w-5xl">
              <div className="lg:flex lg:items-center lg:gap-10 lg:p-0 lg:py-28 text-center text-neutral-700 py-10">
                <div className="flex justify-center py-5">
                  <img className="rounded-2xl lg:max-w-md" src="/music.jpg" />
                </div>
                <div className="lg:max-w-xl lg:text-left">
                  <h4 className="text-xl font-bold  py-2.5 text-sky-500">
                    ABOUT ME
                  </h4>
                  <h3 className="text-2xl font-bold pb-5">
                    A dedicated Front-end Developer based in Salt Lake City,
                    Utah 📍
                  </h3>
                  <p className="text-neutral-500">
                    As a Junior Front-End Developer, I possess an impressive
                    arsenal of skills in HTML, CSS, JavaScript, React, Tailwind,
                    and SCSS. My expertise lies in crafting dynamic, engaging
                    interfaces through writing clean and optimized code and
                    utilizing cutting-edge development tools and techniques. I
                    am also a team player who thrives in collaborating with
                    cross-functional teams to produce outstanding web
                    applications.
                  </p>
                </div>
              </div>
            </div>
          </div>
        </section>

        {/*PROJECTS SECTION*/}
        <section title="projects" id="projects" className="bg-slate-50 px-10">
          <div className="lg:flex lg:justify-center">
            <div className="text-center text-neutral-700 py-10 lg:p-0 lg:py-16 lg:max-w-5xl ">
              <h4 className="text-xl font-bold  pb-10 text-sky-500 lg:pb-10">
                PORTFOLIO
              </h4>
              <ul className="flex flex-col gap-10">
                <li className="bg-white  lg:flex lg:flex-row shadow-lg p-5 rounded-3xl">
                  <div className="flex justify-center">
                    <Image
                      className="rounded-2xl shadow-md lg:max-w-fit"
                      width={400}
                      height={400}
                      cover
                      src="/ecommerce_sc.png"
                      alt="ecommerce project"
                    />
                  </div>
                  <div className="lg:w-full lg:px-10">
                    <h3 className="text-2xl font-bold  p-5">E-Commerce 🛒</h3>
                    <p className="text-neutral-500 px-5">
                      With a focus on simplicity and clean design, this store
                      prioritize user experience, making it easy for customers
                      to find and purchase the products they need.
                    </p>
                    <div className="flex justify-center gap-5 p-5 font-bold">
                      <p className="bg-white shadow-md py-3 px-5">React</p>
                      <p className="bg-white shadow-md py-3 px-5">Redux</p>
                      <p className="bg-white shadow-md py-3 px-5">Sass</p>
                    </div>
                    <div className="flex justify-center gap-10 px-6 font-semibold text-xl">
                      <a
                        className="flex items-center gap-2"
                        href="https://github.com/cc-lau/e-commerce-site"
                        target="_blank"
                      >
                        Code <AiFillGithub />
                      </a>
                      <a
                        className="flex items-center gap-2"
                        href="https://e-commerce-site-six.vercel.app/"
                        target="_blank"
                      >
                        Live Demo <BsBoxArrowUpRight />
                      </a>
                    </div>
                  </div>
                </li>
                <li className="bg-white  lg:flex lg:flex-row shadow-lg p-5 rounded-3xl">
                  <div className="flex justify-center">
                    <Image
                      className="rounded-2xl shadow-md lg:max-w-fit"
                      width={400}
                      height={400}
                      cover
                      src="/password_gen_sc.png"
                      alt="password generator project"
                    />
                  </div>
                  <div className="lg:w-full lg:px-10">
                    <h3 className="text-2xl font-bold  p-5">
                      Password Generator 🔑
                    </h3>
                    <p className="text-neutral-500 px-5">
                      This password generator project is a tool that allows
                      users to generate strong, random passwords with
                      customizable options such as length and character types.
                      It uses built-in JavaScript functions and logic to
                      demonstrate strong JavaScript fundamentals.
                    </p>
                    <div className="flex justify-center gap-5 p-5 font-bold">
                      <p className="bg-white shadow-md py-3 px-5">React</p>
                      <p className="bg-white shadow-md py-3 px-5">Tailwind</p>
                    </div>
                    <div className="flex justify-center gap-10 px-6 font-semibold text-xl">
                      <a
                        className="flex items-center gap-2"
                        href="https://github.com/cc-lau/password-generator"
                        target="_blank"
                      >
                        Code <AiFillGithub />
                      </a>
                      <a
                        className="flex items-center gap-2"
                        href="https://password-generator-cc-lau.vercel.app/"
                        target="_blank"
                      >
                        Live Demo <BsBoxArrowUpRight />
                      </a>
                    </div>
                  </div>
                </li>
                <li className="bg-white  lg:flex  shadow-lg p-5 rounded-3xl lg:flex-row-reverse">
                  <div className="flex justify-center">
                    <Image
                      className="rounded-2xl shadow-md lg:max-w-fit"
                      width={400}
                      height={400}
                      cover
                      src="/youtube-project.png"
                      alt="youtube 2 mp3 project"
                    />
                  </div>
                  <div className="lg:w-full lg:px-10">
                    <h3 className="text-2xl font-bold  p-5">
                      YouTube 2 Mp3 📻
                    </h3>
                    <p className="text-neutral-500 px-5">
                      A Youtube 2 Mp3 website is an online platform that
                      utilizes the YT 2 MP3 API to allow users to download audio
                      from Youtube videos for personal use. The website provides
                      an interface for converting a youtube link and downloading
                      the converted audio.
                    </p>
                    <div className="flex justify-center gap-5 p-5 font-bold">
                      <p className="bg-white shadow-md py-3 px-5">React</p>
                      <p className="bg-white shadow-md py-3 px-5">
                        Vanilla CSS
                      </p>
                    </div>
                    <div className="flex justify-center gap-10 px-6 font-semibold text-xl">
                      <a
                        className="flex items-center gap-2"
                        href="https://github.com/cc-lau/yt-2-mp3"
                        target="_blank"
                      >
                        Code <AiFillGithub />
                      </a>
                      <a
                        className="flex items-center gap-2"
                        href="https://cc-lau.github.io/yt-2-mp3/"
                        target="_blank"
                      >
                        Live Demo <BsBoxArrowUpRight />
                      </a>
                    </div>
                  </div>
                </li>

                <li className="bg-white  lg:flex  shadow-lg p-5 rounded-3xl lg:flex-row-reverse">
                  <div className="flex justify-center">
                    <Image
                      className="rounded-2xl shadow-md lg:max-w-fit"
                      width={400}
                      height={400}
                      cover
                      src="/todo_sc.png"
                      alt="to do app project"
                    />
                  </div>
                  <div className="lg:w-full lg:px-10">
                    <h3 className="text-2xl font-bold  p-5">To-Do App 📅</h3>
                    <p className="text-neutral-500 px-5">
                      A To-Do App is a simple CRUD application that allows users
                      to add, edit and delete tasks. Users are able to sort
                      tasks into projects and sort by certain parameters. This
                      To-Do App demonstrates strong JS fundamentals.
                    </p>
                    <div className="flex justify-center gap-5 p-5 font-bold">
                      <p className="bg-white shadow-md py-3 px-5">JavaScript</p>
                      <p className="bg-white shadow-md py-3 px-5">
                        Vanilla CSS
                      </p>
                    </div>
                    <div className="flex justify-center gap-10 px-6 font-semibold text-xl">
                      <a
                        className="flex items-center gap-2"
                        href="https://github.com/cc-lau/todo-list"
                        target="_blank"
                      >
                        Code <AiFillGithub />
                      </a>
                      <a
                        className="flex items-center gap-2"
                        href="https://cc-lau.github.io/todo-list/"
                        target="_blank"
                      >
                        Live Demo <BsBoxArrowUpRight />
                      </a>
                    </div>
                  </div>
                </li>
              </ul>
            </div>
          </div>
        </section>

        <section title="contact" id="contact" className="bg-white px-10">
          <div className="lg:max-w-5xl lg:flex lg:justify-start m-auto">
            <div className="text-center text-neutral-700 py-10 lg:p-0 lg:py-24 lg:text-left">
              <h4 className="text-2xl font-bold p-2.5 text-sky-500">CONTACT</h4>
              <div className="lg:flex lg:flex-row lg:items-center lg:gap-24">
                <div className="flex justify-center flex-col items-center gap-5 pb-5 lg:pb-0 lg:flex-row">
                  <div className="text-3xl text-sky-500 bg-white rounded-full w-fit p-5 shadow-md">
                    <BiMailSend />
                  </div>
                  <div className="lg:text-left">
                    <h3 className="text-xl font-bold">Mail</h3>
                    <p className="text-neutral-500">
                      christianlau1003@gmail.com
                    </p>
                  </div>
                </div>
                <div className="flex justify-center flex-col items-center gap-5 lg:flex-row">
                  <div className="text-sky-500 text-3xl bg-white rounded-full w-fit p-5 shadow-md">
                    <BsFillTelephoneFill />
                  </div>
                  <div className="lg:text-left">
                    <h3 className="text-xl font-bold">Phone</h3>
                    <p className="text-neutral-500">&#40;385&#41;-436-5835</p>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </section>

        <footer className="bg-zinc-800 text-white p-10 text-center">
          <div className="lg:flex lg:justify-between lg:m-auto lg:max-w-5xl">
            <div>
              <h3 className="font-bold text-lg pb-5">
                Copyright © 2023. All rights are reserved
              </h3>
            </div>
            <div className="text-3xl flex justify-center gap-2">
              <a
                href="https://www.linkedin.com/in/christian-lau-436431260/"
                target="_blank"
              >
                <AiFillLinkedin />
              </a>
              <a href="https://github.com/cc-lau" target="_blank">
                <AiFillGithub />
              </a>
            </div>
          </div>
        </footer>
      </main>
    </>
  );
}
