import React from "react";
import Head from "next/head";
import { AiFillGithub, AiFillLinkedin, AiFillHtml5 } from "react-icons/ai";
import { DiCss3, DiReact } from "react-icons/di";
import { SiTailwindcss, SiSass, SiJavascript } from "react-icons/si";
import { BsBoxArrowUpRight, BsFillTelephoneFill } from "react-icons/bs";
import { BiMailSend } from "react-icons/bi";
import Image from "next/image";

export default function Home() {
  return (
    <>
      <Head>
        <title>Christian Lau Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header className="sticky top-0 z-30 w-full bg-white shadow-xl">
        <nav className="p-8  flex justify-between">
          <h1 className="text-xl font-semibold">christian.dev</h1>
          <ul className="flex items-center">
            <li>
              <a
                className="text-neutral-900 font-semibold px-4 py-2"
                href="#home"
              >
                Home
              </a>
            </li>
            <li>
              <a
                className="text-neutral-900 font-semibold px-4 py-2"
                href="#about"
              >
                About
              </a>
            </li>
            {/*               <li>
                <a
                  className="text-neutral-900 font-semibold px-4 py-2"
                  href="#projects"
                >
                  Projects
                </a>
              </li>
              <li>
                <a
                  className="text-neutral-900 font-semibold px-4 py-2"
                  href="#contact"
                >
                  Contact
                </a>
              </li> */}
          </ul>
        </nav>
      </header>
      <main className="bg-slate-50">
        <section className="min-h-screen px-10">
          <div className="lg:max-w-5xl lg:m-auto lg:pt-28">
            <div className="lg:flex lg:justify-center">
              <div className="lg:flex lg:flex-row-reverse lg:items-center lg:gap-28 text-center pt-10 text-neutral-700">
                <div className="flex justify-center mx-auto rounded-full overflow-hidden min-w-fit">
                  <img
                    className="lg:max-w-lg h-72 lg:min-w-full lg:h-80"
                    src="/profile-good.png"
                  />
                </div>
                <div className="lg:max-w-xl lg:text-left pt-10">
                  <h2 className="lg:text-6xl text-4xl font-bold">
                    Front-End React Developer
                  </h2>
                  <p className="text-lg py-5 leading-8 font-normal text-neutral-500">
                    Hi, I'm Christian Lau. A passionate Front-end React
                    Developer based in Salt Lake City, Utah. 📍
                  </p>
                  <div className="lg:justify-start text-4xl flex justify-center gap-2 py-3">
                    <a
                      href="https://www.linkedin.com/in/christian-lau-436431260/"
                      target="_blank"
                    >
                      <AiFillLinkedin />
                    </a>
                    <a href="https://github.com/cc-lau" target="_blank">
                      <AiFillGithub />
                    </a>
                  </div>
                </div>
              </div>
            </div>
          </div>
          <div className="flex text-neutral-800 justify-center items-center flex-col p-10 lg:p-0 lg:pt-16">
            <h4 className="text-2xl font-semibold text-center py-2 border-b-2 w-fit">
              Tech Stack
            </h4>
            <div className="text-4xl flex flex-wrap justify-center gap-5 py-10">
              <div className=" bg-white rounded-full w-fit p-3 shadow-md">
                <AiFillHtml5 />
              </div>
              <div className=" bg-white rounded-full w-fit p-3 shadow-md">
                {" "}
                <DiCss3 />
              </div>

              <div className=" bg-white rounded-full w-fit p-3 shadow-md">
                {" "}
                <SiJavascript />
              </div>

              <div className=" bg-white rounded-full w-fit p-3 shadow-md">
                {" "}
                <DiReact />
              </div>

              <div className=" bg-white rounded-full w-fit p-3 shadow-md">
                <SiTailwindcss />
              </div>

              <div className=" bg-white rounded-full w-fit p-3 shadow-md">
                {" "}
                <SiSass />
              </div>
            </div>
          </div>
        </section>

        {/* ABOUT ME SECTION */}
        <section className="bg-white px-10">
          <div className="lg:flex lg:justify-center">
            <div className="lg:max-w-5xl">
              <div className="lg:flex lg:items-center lg:gap-10 lg:p-0 lg:py-28 text-center text-neutral-700 py-10">
                <div className="flex justify-center py-5">
                  <img className="rounded-2xl lg:max-w-md" src="/music.jpg" />
                </div>
                <div className="lg:max-w-xl lg:text-left">
                  <h4 className="text-xl font-bold  py-2.5 text-sky-500">
                    ABOUT ME
                  </h4>
                  <h3 className="text-2xl font-bold pb-5">
                    A dedicated Front-end Developer based in Salt Lake City,
                    Utah 📍
                  </h3>
                  <p className="text-neutral-500">
                    As a Junior Front-End Developer, I possess an impressive
                    arsenal of skills in HTML, CSS, JavaScript, React, Tailwind,
                    and SCSS. My expertise lies in crafting dynamic, engaging
                    interfaces through writing clean and optimized code and
                    utilizing cutting-edge development tools and techniques. I
                    am also a team player who thrives in collaborating with
                    cross-functional teams to produce outstanding web
                    applications.
                  </p>
                </div>
              </div>
            </div>
          </div>
        </section>

        {/*PROJECTS SECTION*/}
        <section className="bg-slate-50 px-10">
          <div className="lg:flex lg:justify-center">
            <div className="text-center text-neutral-700 py-10 lg:p-0 lg:py-16 lg:max-w-5xl ">
              <h4 className="text-xl font-bold  pb-10 text-sky-500 lg:pb-10">
                PORTFOLIO
              </h4>
              <ul>
                <li className="bg-white  lg:flex lg:flex-row shadow-lg p-5 rounded-3xl">
                  <div className="flex justify-center">
                    <Image
                      className="rounded-2xl shadow-md lg:max-w-fit"
                      width={400}
                      height={400}
                      cover
                      src="/youtube-project.png"
                    />
                  </div>
                  <div className="lg:w-full lg:px-10">
                    <h3 className="text-2xl font-bold  p-5">
                      YouTube 2 Mp3 📻
                    </h3>
                    <p className="text-neutral-500 px-5">
                      A Youtube 2 Mp3 website is an online platform that
                      utilizes the YT 2 MP3 API to allow users to download audio
                      from Youtube videos for personal use. The website provides
                      an interface for converting a youtube link and downloading
                      the converted audio.
                    </p>
                    <div className="flex justify-center gap-10 p-5 font-bold">
                      <p className="bg-white shadow-md py-3 px-5">React</p>
                      <p className="bg-white shadow-md py-3 px-5">
                        Vanilla CSS
                      </p>
                    </div>
                    <div className="flex justify-center gap-10 px-6 font-semibold text-xl">
                      <a
                        className="flex items-center gap-2"
                        href="https://github.com/cc-lau/yt-2-mp3"
                        target="_blank"
                      >
                        Code <AiFillGithub />
                      </a>
                      <a
                        className="flex items-center gap-2"
                        href="https://cc-lau.github.io/yt-2-mp3/"
                        target="_blank"
                      >
                        Live Demo <BsBoxArrowUpRight />
                      </a>
                    </div>
                  </div>
                </li>
              </ul>
            </div>
          </div>
        </section>

        <section className="bg-white px-10">
          <div className="lg:max-w-5xl lg:flex lg:justify-start m-auto">
            <div className="text-center text-neutral-700 py-10 lg:p-0 lg:py-24 lg:text-left">
              <h4 className="text-2xl font-bold p-2.5 text-sky-500">CONTACT</h4>
              <div className="lg:flex lg:flex-row lg:items-center lg:gap-24">
                <div className="flex justify-center flex-col items-center gap-5 pb-5 lg:pb-0 lg:flex-row">
                  <div className="text-3xl text-sky-500 bg-white rounded-full w-fit p-5 shadow-md">
                    <BiMailSend />
                  </div>
                  <div className="lg:text-left">
                    <h3 className="text-xl font-bold">Mail</h3>
                    <p className="text-neutral-500">
                      christianlau1003@gmail.com
                    </p>
                  </div>
                </div>
                <div className="flex justify-center flex-col items-center gap-5 lg:flex-row">
                  <div className="text-sky-500 text-3xl bg-white rounded-full w-fit p-5 shadow-md">
                    <BsFillTelephoneFill />
                  </div>
                  <div className="lg:text-left">
                    <h3 className="text-xl font-bold">Phone</h3>
                    <p className="text-neutral-500">&#40;385&#41;-436-5835</p>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </section>

        <footer className="bg-zinc-800 text-white p-10 text-center">
          <div className="lg:flex lg:justify-between lg:m-auto lg:max-w-5xl">
            <div>
              <h3 className="font-bold text-lg pb-5">
                Copyright © 2023. All rights are reserved
              </h3>
            </div>
            <div className="text-3xl flex justify-center gap-2">
              <a
                href="https://www.linkedin.com/in/christian-lau-436431260/"
                target="_blank"
              >
                <AiFillLinkedin />
              </a>
              <a href="https://github.com/cc-lau" target="_blank">
                <AiFillGithub />
              </a>
            </div>
          </div>
        </footer>
      </main>
    </>
  );
}
